comps/urls.py
from django.urls import path
from . import views

app_name = 'comps'

urlpatterns = [
    path('', views.all_comps, name="all_comps"),
    path('create/', views.create_comp, name='create_comp'),
    path('<int:comp_id>/', views.comp_detail, name="comp_detail"),
    path('<int:comp_id>/clear', views.clear_comp, name="clear_comp"),
    path('<int:comp_id>/edit', views.edit_comp, name="edit_comp"),
    path('<int:comp_id>/thisyear', views.this_year_comp, name="this_year_comp"),
    path('<int:comp_id>/heats', views.comp_heats, name="comp_heats"),
    path('<int:comp_id>/heats/?dancer=<int:dancer_id>', views.dancer_heats, name="dancer_heats"),
    path('<int:comp_id>/heats/?couple=<int:couple_id>', views.couple_heats, name="couple_heats"),
    path('<int:comp_id>/save_heatlists', views.save_heatlists, name="save_heatlists"),
    path('<int:comp_id>/save_scoresheets', views.save_scoresheets, name="save_scoresheets"),
    path('<int:comp_id>/dancers', views.dancers, name="dancers"),
    path('<int:comp_id>/couples', views.couples, name="couples"),
    path('<int:comp_id>/delete_noheat_couples', views.delete_noheat_couples, name="delete_noheat_couples"),
    path('<int:comp_id>/load_dancers', views.load_dancers, name="load_dancers"),
    path('<int:comp_id>/load_heats', views.load_heats, name="load_heats"),
    path('<int:comp_id>/load_heats/<int:multis_only>', views.load_heats, name="load_heats"),
    path('<int:comp_id>/load_scoresheets', views.load_scoresheets, name="load_scoresheets"),
    path('<int:comp_id>/create_heat', views.create_heat, name="create_heat"),
    path('<int:comp_id>/create_heat/?couple=<int:couple_id>', views.create_heat, name="create_heat"),
    path('<int:comp_id>/resolve_dancers', views.resolve_dancers, name="resolve_dancers"),
    path('<int:comp_id>/mismatch_heats', views.resolve_mismatches, name="resolve_mismatches"),
    path('<int:comp_id>/heatlist_errors', views.show_heatlist_errors, name="show_heatlist_errors"),
    path('<int:comp_id>/scoresheet_errors', views.show_scoresheet_errors, name="show_scoresheet_errors"),
    path('<int:comp_id>/update_elo_ratings', views.update_elo_ratings, name="update_elo_ratings"),
    path('<int:comp_id>/mismatch_heats/<int:wider_search>', views.resolve_mismatches, name="resolve_mismatches"),
    path('<int:comp_id>/duplicate_entries', views.fix_dup_entries, name="fix_dup_entries"),
    path('<int:comp_id>/bad_couple_type', views.fix_couple_type, name="fix_couple_type"),
    path('<int:comp_id>/bad_couple_type/<int:count>', views.fix_couple_type, name="fix_couple_type"),
    path('heat/<int:heat_id>/', views.heat, name="heat"),
    path('heat/<int:heat_id>/<int:sort_mode>', views.heat, name="heat"),
    path('heat/edit/<int:heat_id>/', views.edit_heat, name="edit_heat"),
    path('heat/<int:heat_id>/add_couple/<int:couple_id>/', views.add_couple_to_heat, name="add_couple_to_heat"),
    path('heat_entry/<int:entry_id>/', views.edit_heat_entry, name="edit_heat_entry"),
    path('clear_scoresheet_error/<int:error_id>/', views.delete_scoresheet_error, name="delete_scoresheet_error"),
    path('clear_heatlist_error/<int:error_id>/', views.delete_heatlist_error, name="delete_heatlist_error"),
    path('check_heatlist_error/<int:error_id>/', views.check_heatlist_error, name="check_heatlist_error"),
    path('fix_scoresheet_error/<int:error_id>/', views.repair_scoresheet_error, name="repair_scoresheet_error"),
    # these are maintenance URLs -
    path('<int:comp_id>/combine_heats', views.combine_heats, name="combine_heats"),
    path('<int:comp_id>/null_entries', views.fix_null_entries, name="fix_null_entries"),
]

dancesport_tracker/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings

from rankings import views

app_name = 'rankings'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurabl
    path('', views.home, name="home"),
    path('login/', views.loginuser, name="loginuser"),
    path('logout/', views.logoutuser, name="logoutuser"),
    path('elo/', views.show_elo_ratings, name="show_elo_ratings"),
    path('elo_recalc/', views.recalc_elo_ratings, name="recalc_elo_ratings"),
    path('elo_edit/<int:couple_pk>/<str:dance_style>', views.edit_elo_ratings, name="edit_elo_ratings"),
    path('scoring', views.scoring, name="scoring"),
    path('dancers/', views.all_dancers, name="all_dancers"),
    path('dancers/alias_list/<int:level>/', views.alias_dancers, name="alias_dancers"),
    path('dancers/alias/<int:hld_pk>/', views.aliases_for_dancer, name="aliases_for_dancer"),
    path('dancers/accept_alias/<int:hld_pk>', views.accept_alias, name="accept_alias"),
    path('dancers/reject_alias/<int:hld_pk>', views.reject_alias, name="reject_alias"),
    path('dancers/<int:dancer_pk>/', views.view_dancer, name='view_dancer'),
    path('dancers/<int:dancer_pk>/<int:couple_pk>/', views.view_dancer, name='view_dancer'),    
    path('dancers/edit/<int:dancer_pk>', views.edit_dancer, name='edit_dancer'),
    path('dancers/create/', views.create_dancer, name='create_dancer'),
    path('dancers/create/<str:name_str>/<int:comp_pk>', views.create_dancer, name='create_dancer'),
    path('couples/', views.all_couples, name="all_couples"),
    path('couples/<int:couple_pk>', views.view_couple, name='view_couple'),
    path('couples/<int:couple_pk>/combine/<int:couple2_pk>', views.combine_couples, name='combine_couples'),
    path('couples/flip/<int:couple_pk>', views.flip_couple, name='flip_couple'),
    path('couples/delete/<int:couple_pk>', views.delete_couple, name='delete_couple'),
    path('couples/edit/<int:couple_pk>', views.edit_couple, name='edit_couple'),
    path('couples/change_type/<int:couple_pk>', views.change_couple_type, name='change_couple_type'),
    path('couples/create/', views.create_couple, name='create_couple'),
    path('couples/create/<str:couple_type>/<int:dancer_pk>/<int:dancer_position>/', views.create_couple, name='create_couple'),
    path('couples/create/<str:couple_type>/<int:dancer_pk>/<int:dancer_position>/<int:partner_pk>', views.create_couple, name='create_couple'),
    path('comps/', include('comps.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rankings/models.py
from django.db import models
from datetime import date

# Create your models here.
class Dancer(models.Model):
    # name fields
    name_first = models.CharField(max_length=25)
    name_middle = models.CharField(max_length=25, blank=True)
    name_last = models.CharField(max_length=50)

    # dancer type has choices
    PRO = 'PRO'
    ADULT_AMATEUR = 'AM'
    JUNIOR_AMATEUR = 'JR'
    DANCER_TYPE_CHOICES = [
        (PRO, 'Professional'),
        (ADULT_AMATEUR, 'Amateur'),
        (JUNIOR_AMATEUR , 'Junior'),
    ]
    dancer_type = models.CharField(
        max_length=3,
        choices=DANCER_TYPE_CHOICES,
        default=PRO,
    )

    name_fix_date = models.DateField(default=date(2021,4,19))

    def __str__(self):
        if len(self.name_middle) > 0:
            return self.name_last + ", " + self.name_first + " " + self.name_middle
        else:
            return self.name_last + ", " + self.name_first

    def __lt__(self, d):
        if self.name_last == d.name_last:
            return self.name_first < d.name_first
        else:
            return self.name_last < d.name_last

    class Meta:
        ordering = ["name_last", "name_first"]


class Couple(models.Model):
    dancer_1 = models.ForeignKey('Dancer', on_delete=models.CASCADE, related_name="leader_or_student")
    dancer_2 = models.ForeignKey('Dancer', on_delete=models.CASCADE, related_name="follower_or_instructor")

    # Couple type has choices
    PRO_COUPLE = 'PRC'
    PRO_AM_COUPLE = 'PAC'
    JR_PRO_AM_COUPLE = 'JPC'
    AMATEUR_COUPLE = 'AMC'
    JR_AMATEUR_COUPLE = 'JAC'
    COUPLE_TYPE_CHOICES = [
        (PRO_COUPLE, 'Professionals'),
        (PRO_AM_COUPLE, 'Pro-Am'),
        (JR_PRO_AM_COUPLE , 'Junior_Pro-Am'),
        (AMATEUR_COUPLE, 'Amateurs'),
        (JR_AMATEUR_COUPLE , 'Junior_Amateurs'),
    ]
    couple_type = models.CharField(
        max_length=3,
        choices=COUPLE_TYPE_CHOICES,
        default=PRO_AM_COUPLE,
    )

    def __str__(self):
        return self.dancer_1.__str__() + " and " + self.dancer_2.__str__()

    def __lt__(self, c):
        if self.dancer_1 == c.dancer_1:
            if self.dancer_2 == c.dancer_2:
                return self.couple_type < c.couple_type
            else:
                return self.dancer_2 < c.dancer_2
        else:
            return self.dancer_1 < c.dancer_1

    class Meta:
        ordering = ["dancer_1"]

rankings/models/elo_rating.py
from django.db import models
from .couple import Couple
from comps.models.heat import DANCE_STYLE_CHOICES


class EloRating(models.Model):
    couple = models.ForeignKey('Couple', on_delete=models.CASCADE)
    style = models.CharField(max_length = 4, choices = DANCE_STYLE_CHOICES, default="UNK")
    num_events = models.IntegerField(default=0)
    value = models.FloatField(null=True, default=None)
    
    def __str__(self):
        return str(self.couple) + " - " + self.style + ": " + str(round(self.value, 2))
    
    def __lt__(self, v):
        return self.value < v

rankings/views/alias_dancers.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from comps.forms import HeatListDancerForm
from comps.models.comp import Comp
from comps.models.heat_entry import Heat_Entry
from comps.models.heatlist_dancer import Heatlist_Dancer
from rankings.couple_matching import split_name
from rankings.models import Dancer


def alias_dancers(request, level=2):
    if not request.user.is_superuser:
        return render(request, 'rankings/permission_denied.html')
    
    print("Looking for Heatlist Dancers with no comp")
    no_comp_list = Heatlist_Dancer.objects.filter(comp__isnull=True)
    if len(no_comp_list) > 0:
        print("Removing " + str(len(no_comp_list)) + ' entries')
        for d in no_comp_list:
            d.delete()    
    
    alias_dancers = Heatlist_Dancer.objects.exclude(alias__isnull=True).order_by('name', 'comp__start_date')

    if request.method == 'GET':
        f = HeatListDancerForm()
        if level == 2:
            doubles = list()
            for i in range(1, len(alias_dancers)):
                if alias_dancers[i-1].name == alias_dancers[i].name and alias_dancers[i-1].alias == alias_dancers[i].alias:
                    doubles.append(alias_dancers[i])
            paginator = Paginator(doubles, 16)
        else:
            paginator = Paginator(alias_dancers, 16)        

    else: # POST
        f = HeatListDancerForm(request.POST)
        if not f.is_valid():
            return redirect (comps.all_comps)
        else:
            filter_parms = f.cleaned_data
            if len(filter_parms['comp']) > 0:
                alias_dancers = alias_dancers.filter(comp__title__contains=filter_parms['comp'])
            if len(filter_parms['alias']) > 0:
                alias_dancers = alias_dancers.filter(alias__name_last__contains=filter_parms['alias'])
            if len(filter_parms['name']) > 0:
                alias_dancers = alias_dancers.filter(name__contains=filter_parms['name'])             
            
            paginator = Paginator(alias_dancers, 16)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'rankings/alias_dancers.html', {'form': f, 'page_obj': page_obj, 'level': level })


def aliases_for_dancer(request, hld_pk):
    if not request.user.is_superuser:
        return render(request, 'rankings/permission_denied.html')

    # get the heatlist dancer and the dancer by alias
    heatlist_dancer = get_object_or_404(Heatlist_Dancer, pk=hld_pk)
    dancer = get_object_or_404(Dancer, pk=heatlist_dancer.alias.id)
    dancer_aliases = Heatlist_Dancer.objects.filter(alias=heatlist_dancer.alias)

    all_comps = Comp.objects.all().order_by('-start_date')
    comps_for_dancer = list()
    for comp in all_comps:
        # if dancer's name has been corrected after this comp's start date, quit loop
        if comp.start_date < dancer.name_fix_date:
            break
        # if the dancer was in this comp
        if Heat_Entry.objects.filter(heat__comp=comp).filter(Q(couple__dancer_1=dancer) | Q(couple__dancer_2=dancer)).count() > 0:
            # and had an alias in that comp
            matches = dancer_aliases.filter(comp=comp)
            # add the alias to the list
            if matches.count() > 0:
                comps_for_dancer.append(matches.first())
            else: # add a "no name alias" to the list
                no_name_hld = Heatlist_Dancer()
                no_name_hld.name = ""
                no_name_hld.code = "No Code"
                no_name_hld.alias = dancer
                no_name_hld.comp = comp
                comps_for_dancer.append(no_name_hld)

    paginator = Paginator(comps_for_dancer, 16)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'rankings/alias_dancers.html', {'page_obj': page_obj, 'level': 1 })


def accept_alias(request, hld_pk):
    if not request.user.is_superuser:
        return render(request, 'rankings/permission_denied.html')

    # get the heatlist dancer and format the new name
    heatlist_dancer = get_object_or_404(Heatlist_Dancer, pk=hld_pk)
    name_last, name_first, name_middle = split_name(heatlist_dancer.name)

    # get the dancer object referenced by alias
    dancer = heatlist_dancer.alias
    dancer.name_last = name_last
    dancer.name_first = name_first
    dancer.name_middle = name_middle
    dancer.name_fix_date = heatlist_dancer.comp.start_date
    dancer.save()

    # now that dancer object has been updated with a new name, delete these aliases
    aliases_to_remove = Heatlist_Dancer.objects.filter(name=heatlist_dancer.name).filter(alias=heatlist_dancer.alias)
    for a in aliases_to_remove:
        hld_object = a
        hld_object.delete()

    return redirect('view_dancer', dancer.id)


def reject_alias(request, hld_pk):
    if not request.user.is_superuser:
        return render(request, 'rankings/permission_denied.html')

    # get the heatlist dancer whose alias has been rejected
    heatlist_dancer = get_object_or_404(Heatlist_Dancer, pk=hld_pk)

    # get the dancer object referenced by alias
    dancer = heatlist_dancer.alias
    dancer.name_fix_date = heatlist_dancer.comp.start_date
    dancer.save()

    # remove all matching heatlist_dancer objects
    aliases_to_remove = Heatlist_Dancer.objects.filter(name=heatlist_dancer.name).filter(alias=heatlist_dancer.alias)
    for a in aliases_to_remove:
        hld_object = a
        hld_object.delete()

    return redirect('alias_dancers', 2)

rankings/views/calc_teacher_rankings.py
#from django.core.cache import cache
#from django.core.paginator import Paginator
#from django.shortcuts import render, redirect, get_object_or_404
#from rankings.tasks import calc_teacher_ratings
#from comps.models.comp import Comp
#from comps.models.heat import Heat, DANCE_STYLE_CHOICES
#from comps.models.heat_entry import Heat_Entry
#from operator import itemgetter
#from decimal import Decimal


#def calc_teacher_rankings(request):
    #styles = Heat.DANCE_STYLE_CHOICES
    #style_choices = list()
    #for s in styles:
        #style_choices.append(s[0])
    #style_labels = list()
    #for s in styles:
        #style_labels.append(s[1])

    #if request.method == "GET":
        #page_number = request.GET.get('page')

        #heat_style = request.GET.get('style')
        #if heat_style is None:
            #heat_style = "SMOO"
        #index = style_choices.index(heat_style)
        #style = style_labels[index]

        #last_name = request.GET.get('last_name')

        #cache_key = heat_style

    #else:
        #page_number = 1

        #style = request.POST.get("style")
        #index = style_labels.index(style)
        #heat_style = DANCE_STYLE_CHOICES[index][0]

        #current_url = request.path
        #url_string = current_url + "?style=" + heat_style

        #last_name = request.POST.get("last_name")
        #if last_name is not None:
            #url_string += "&last_name=" + last_name
        #return redirect(url_string)

    #teacher_stats = cache.get(cache_key)

    #if teacher_stats is None:
        ## cache miss - calculate rankings and store in cache
        #result = calc_teacher_ratings.delay(heat_style, cache_key)
        #return render(request, 'rankings/calc_teacher_ranking_progress.html', context={'task_id': result.task_id, 'styles': style_labels, 'selected_style': style})

    ## filter by last name if necessary and paginate the results
    #if last_name is not None:
        #if len(last_name) > 0:
            #teacher_stats = list(filter(lambda dancer: last_name.lower() in dancer['instructor'].name_last.lower(), teacher_stats))

    #paginator = Paginator(teacher_stats, 16)
    #page_number = request.GET.get('page')
    #page_obj = paginator.get_page(page_number)
    #return render(request, 'rankings/calc_teacher_rankings.html', {'page_obj': page_obj, 'styles': style_labels, 'selected_style': style})

rankings/templates/rankings/all_couples.html
{% extends "rankings/base.html" %}

{% block content %}

  <div class="row">
    <div class="col-12">
      <h2 class="text-center">Couples</h2>
      {% if heat %}
        <h4 class='text-center'>Add couple to <a href="{% url 'comps:heat' heat.id %}">{{ heat }}</a></h4>
      {% endif %}
    </div>
  </div>

  {{ error }}
  
  {% include "rankings/pagination.html" %}

  <div class="row">
    <div class="col-12 col-lg-8 offset-lg-2 p-0 border border-dark">
      <table class="table table-bordered table-sm mb-0">
        <thead class="thead-dark">
          <tr>
            <th class='text-center'>Dancer 1</th>
            <th></th>
            <th class='text-center'>Dancer 2</th>
            <th class='text-center'>Couple Type</th>
            <th class='text-center'>Action</th>
          </tr>
        </thead>
        <tbody>
          <form class="mx-auto" id='couple-filter-form' method="POST">
            {% csrf_token %}
            <tr class="table-primary">
              <td colspan="3"  id='name-filter' class="text-center">{{ form.name }}</td>
              <td id='couple-type-filter' class="text-center">{{ form.couple_type }}</td>
              <td class="text-center"><input  type="submit" name="btn-submit" value="&#128269;"/></td>
            </tr>
          </form>
          {% for couple in page_obj %}
          <tr>
            <td class='text-center'>
              <a class='text-dark' href="{% url 'view_dancer' couple.dancer_1.id %}"> {{ couple.dancer_1 }}</a>
            </td>
            <td class='text-center d-sm-none'>-</td>
            <td class='text-center d-none d-sm-table-cell'>and</td>
            <td class='text-center'>
              <a class='text-dark' href="{% url 'view_dancer' couple.dancer_2.id %}">{{ couple.dancer_2 }}</a>
            </td>
            <td class='text-center'>{{ couple.get_couple_type_display }}</td>
            <td class='text-center'>
              <a class='btn btn-primary btn-sm' href="{% url 'view_couple' couple.id %}">View</a>
              {% if heat %}
                  <a class='btn btn-warning btn-sm' href="{% url 'comps:add_couple_to_heat' heat.id couple.id %}">Add to Heat</a>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      {% if show_admin_buttons %}
        <div class="text-center my-3">
          <a class="btn btn-primary" href="{% url 'create_couple' %}">Add Couple</a>
        </div>
      {% endif %}
    </div>
  </div>


{% endblock %}

rankings/templates/rankings/change_couple_type.html
{% extends "rankings/base.html" %}

{% block content %}

<h2 class='text-center'>{{ couple }}</h2>
<h3 class='text-center'>Couple Type: {{ couple.get_couple_type_display }}</h3>
<h4 class='text-center'>Couple Rating: {{rating}}</h4>
<br />

<div class="row">
  <div class="col-4 offset-4 border border-dark">
    <h3 class="text-center">Edit Couple Type</h3>
    <p>{{ error }}</p>

    <form method="POST">
      {% csrf_token %}
      <div class="text-center form-group">
        <label class="label">Type</label>
          {{ form.couple_type}}
      </div>
      <div class="text-center mt-3">
        <input class="btn btn-primary" type="submit" name="submit" value = "Save"/>
      </div>
    </form>
  </div>
</div>


{% endblock %}

rankings/templates/rankings/edit_couple.html
{% extends "rankings/base.html" %}

{% block content %}

<h2 class='text-center'>{{ couple }}</h2>
<h3 class='text-center'>{{ couple.get_couple_type_display }}</h3>
<br />

<div class="row">
  <div class="col-4 offset-4 border border-dark">
    <h3 class="text-center">Edit Profile</h3>
    <p>{{ error }}</p>

    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
          <label>Leader</label>
          {{ form.dancer_1}}
      </div>
      <div class="form-group">
        <label class="label">Follower</label>
          {{ form.dancer_2}}
      </div>
      <div class="form-group">
        <label class="label">Type</label>
          {{ form.couple_type}}
      </div>
      <div class="text-center mt-3">
        <input class="btn btn-primary" type="submit" name="submit" value = "Save"/>
      </div>
      <div class="text-center mt-2">
        <input class="btn btn-danger" type="submit" name="submit" value="Delete Couple" onclick="return confirm('Are you sure?')" />
      </div>
    </form>
  </div>
</div>


{% endblock %}

rankings/templates/rankings/login.html
{% extends "rankings/base.html" %}

{% block content %}

<div class="row">
  <div class="col-4 offset-md-4 text-center">
    <h2 class="text-center">Login</h2>

    <h3>{{ error }}</h3>

    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="text-center my-1">
        <button type="submit">Login</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

rankings/templates/rankings/view_couple.html
{% extends "rankings/base.html" %}

{% block content %}

<!-- display couple names as individual dancers with links to dancer page -->
<!-- <h2 class='text-center'>{{ couple }}</h2> -->
<h2 class='text-center'>
  <a class="text-dark" href="{% url 'view_dancer' couple.dancer_1.id %}">{{couple.dancer_1 }}</a> and <a class="text-dark" href="{% url 'view_dancer' couple.dancer_2.id %}">{{ couple.dancer_2 }}</a>
</h2>
<h3 class='text-center'>Couple Type: {{ couple.get_couple_type_display }}</h3>

{% if show_admin_buttons %}
  <div class="text-center my-3">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownActionButton" data-toggle="dropdown">Modify</button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'change_couple_type' couple.id %}">Change Type</a>
      <a class="dropdown-item" href="{% url 'edit_couple' couple.id %}">Edit All Fields</a>
      <a class="dropdown-item" href="{% url 'flip_couple' couple.id %}">Flip</a>
    </div>
  </div>
{% endif %}

<div class="row">

  <div class="col-12 col-lg-4 px-3 border border-dark">
    <h3 class="text-center">Couple's Elo Ratings</h3>
    <table class="table table-bordered table-sm">
      <tr>
        <th class="text-center">Style</th>
        <th class="text-center">Events</th>
        <th class="text-center">Rating</th>
      </tr>

      {% for r in elo_ratings %}
        <tr>
          <td class="text-center"><a href="{% url 'show_elo_ratings' %}?type={{ r.couple.couple_type }}&style={{ r.style }}">{{ r.get_style_display }}</a></td>
          <td class="text-center">{{ r.num_events}}</td>
          {% if show_admin_buttons %}
            <td class="text-center"><a href="{% url 'edit_elo_ratings' r.couple.id r.style %}">{{ r.value|floatformat:2}}</a></td>
          {% else %}
            <td class="text-center">{{ r.value|floatformat:2}}</td>
          {% endif %}  
        </tr>
      {% endfor %}
    </table>
  </div>

  <div class="col-12 col-lg-8 px-3 border border-dark">
    <h3 class="text-center">Couple's Competitions</h3>
    <table class="table table-bordered table-sm">
      <tr>
        <th class="text-center">Start Date</th>
        <th class="text-center">Title</th>
        <th class="text-center d-none d-md-table-cell">Location</th>
        <th class="text-center">Heats</th>
      </tr>

      {% for comp in comps_for_couple %}
      <tr>
        <td class="text-center">{{ comp.start_date }}</td>
        <td class="text-center"><a href="{% url 'comps:comp_detail' comp.id %}">{{ comp.title }}</a></td>
        <td class="text-center d-none d-md-table-cell">{{ comp.location}}</td>
        {% if comp.process_state == comp.RESULTS_RESOLVED or comp.process_state == comp.ELO_RATINGS_UPDATED %}
          <td class="text-center"><a class="btn btn-outline-dark btn-sm" role="button" href="{% url 'comps:couple_heats' comp.id couple.id %}">View Results</a></td>
        {% else %}
          <td class="text-center"><a class="btn btn-outline-dark btn-sm" role="button" href="{% url 'comps:couple_heats' comp.id couple.id %}">View Heats</a></td>
        {% endif %}
      </tr>
      {% endfor %}
    </table>
    {% if show_admin_buttons %}
      <div class="text-center my-3">
        {% if comps_with_mismatches %}
          {% if comps_with_mismatches|length > 1%}
            <span class="dropdown">
              <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown">Go to Comp</button>
              <span class="dropdown-menu">
                {% for comp in comps_with_mismatches %}
                  <a class="dropdown-item" href="{% url 'comps:resolve_mismatches' comp.id%}">{{comp.title}}</a>
                {% endfor %}
              </span>
            </span>
          {% else %}
            <a class="btn btn-secondary btn-sm" href="{% url 'comps:resolve_mismatches' comps_with_mismatches.0.id %}">Go To Comp</a>
          {% endif %}
        {% endif %}
      </div>
    {% endif %}
  </div>
</div>

{% endblock %}

rankings/templates/rankings/viewdancer.html
{% extends "rankings/base.html" %}

{% block content %}

<h2 class='text-center'>{{ dancer }}</h2>
<h3 class='text-center'>Dancer Category: {{ dancer.get_dancer_type_display }}</h3>
<br />

<div class="row">
  <div class="col-8 offset-2 border border-dark">
    <h3 class="text-center">Partnerships</h3>
    <table class="table table-bordered table-sm">
      <tr>
        <th>Dancer 1</th>
        <th></th>
        <th>Dancer 2</th>
        <th>Category</th>
        <th>Action</th>
      </tr>

      {% for couple in couples %}
      <tr>
        <td>{{ couple.dancer_1 }}</td>
        <td>and</td>
        <td>{{ couple.dancer_2 }}</td>
        <td>{{ couple.get_couple_type_display }}</td>
        <td>
          <a class="btn btn-primary btn-sm" href="{% url 'viewcouple' couple.id %}">View</a>
          <a class="btn btn-secondary btn-sm" href="{% url 'editcouple' couple.id %}">Edit</a>
        </td>
      </tr>
      {% endfor %}
    </table>
    <div class="text-center mt-3">
      <a class="btn btn-primary" href="{% url 'createcouple' %}">Add Couple</a>
    </div>
  </div>
</div>







{% endblock %}