comps/urls.py
from django.urls import path
from . import views

app_name = 'comps'

urlpatterns = [
    path('', views.all_comps, name="all_comps"),
    path('create/', views.create_comp, name='create_comp'),
    path('<int:comp_id>/', views.comp_detail, name="comp_detail"),
    path('<int:comp_id>/clear', views.clear_comp, name="clear_comp"),
    path('<int:comp_id>/edit', views.edit_comp, name="edit_comp"),
    path('<int:comp_id>/thisyear', views.this_year_comp, name="this_year_comp"),
    path('<int:comp_id>/heats', views.comp_heats, name="comp_heats"),
    path('<int:comp_id>/heats/?dancer=<int:dancer_id>', views.dancer_heats, name="dancer_heats"),
    path('<int:comp_id>/heats/?couple=<int:couple_id>', views.couple_heats, name="couple_heats"),
    path('<int:comp_id>/save_heatlists', views.save_heatlists, name="save_heatlists"),
    path('<int:comp_id>/save_scoresheets', views.save_scoresheets, name="save_scoresheets"),
    path('<int:comp_id>/dancers', views.dancers, name="dancers"),
    path('<int:comp_id>/couples', views.couples, name="couples"),
    path('<int:comp_id>/delete_noheat_couples', views.delete_noheat_couples, name="delete_noheat_couples"),
    path('<int:comp_id>/load_dancers', views.load_dancers, name="load_dancers"),
    path('<int:comp_id>/load_heats', views.load_heats, name="load_heats"),
    path('<int:comp_id>/load_heats/<int:multis_only>', views.load_heats, name="load_heats"),
    path('<int:comp_id>/load_scoresheets', views.load_scoresheets, name="load_scoresheets"),
    path('<int:comp_id>/create_heat', views.create_heat, name="create_heat"),
    path('<int:comp_id>/create_heat/?couple=<int:couple_id>', views.create_heat, name="create_heat"),
    path('<int:comp_id>/resolve_dancers', views.resolve_dancers, name="resolve_dancers"),
    path('<int:comp_id>/mismatch_heats', views.resolve_mismatches, name="resolve_mismatches"),
    path('<int:comp_id>/heatlist_errors', views.show_heatlist_errors, name="show_heatlist_errors"),
    path('<int:comp_id>/scoresheet_errors', views.show_scoresheet_errors, name="show_scoresheet_errors"),
    path('<int:comp_id>/update_elo_ratings', views.update_elo_ratings, name="update_elo_ratings"),
    path('<int:comp_id>/mismatch_heats/<int:wider_search>', views.resolve_mismatches, name="resolve_mismatches"),
    path('<int:comp_id>/duplicate_entries', views.fix_dup_entries, name="fix_dup_entries"),
    path('<int:comp_id>/bad_couple_type', views.fix_couple_type, name="fix_couple_type"),
    path('<int:comp_id>/bad_couple_type/<int:count>', views.fix_couple_type, name="fix_couple_type"),
    path('heat/<int:heat_id>/', views.heat, name="heat"),
    path('heat/<int:heat_id>/<int:sort_mode>', views.heat, name="heat"),
    path('heat/edit/<int:heat_id>/', views.edit_heat, name="edit_heat"),
    path('heat/<int:heat_id>/add_couple/<int:couple_id>/', views.add_couple_to_heat, name="add_couple_to_heat"),
    path('heat_entry/<int:entry_id>/', views.edit_heat_entry, name="edit_heat_entry"),
    path('clear_scoresheet_error/<int:error_id>/', views.delete_scoresheet_error, name="delete_scoresheet_error"),
    path('clear_heatlist_error/<int:error_id>/', views.delete_heatlist_error, name="delete_heatlist_error"),
    path('check_heatlist_error/<int:error_id>/', views.check_heatlist_error, name="check_heatlist_error"),
    path('fix_scoresheet_error/<int:error_id>/', views.repair_scoresheet_error, name="repair_scoresheet_error"),
    # these are maintenance URLs -
    path('<int:comp_id>/combine_heats', views.combine_heats, name="combine_heats"),
    path('<int:comp_id>/null_entries', views.fix_null_entries, name="fix_null_entries"),
]

dancesport_tracker/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings

from rankings import views

app_name = 'rankings'

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^celery-progress/', include('celery_progress.urls')),  # the endpoint is configurabl
    path('', views.home, name="home"),
    path('login/', views.loginuser, name="loginuser"),
    path('logout/', views.logoutuser, name="logoutuser"),
    path('elo/', views.show_elo_ratings, name="show_elo_ratings"),
    path('elo_recalc/', views.recalc_elo_ratings, name="recalc_elo_ratings"),
    path('elo_edit/<int:couple_pk>/<str:dance_style>', views.edit_elo_ratings, name="edit_elo_ratings"),
    path('scoring', views.scoring, name="scoring"),
    path('dancers/', views.all_dancers, name="all_dancers"),
    path('dancers/alias_list/<int:level>/', views.alias_dancers, name="alias_dancers"),
    path('dancers/alias/<int:hld_pk>/', views.aliases_for_dancer, name="aliases_for_dancer"),
    path('dancers/accept_alias/<int:hld_pk>', views.accept_alias, name="accept_alias"),
    path('dancers/reject_alias/<int:hld_pk>', views.reject_alias, name="reject_alias"),
    path('dancers/<int:dancer_pk>/', views.view_dancer, name='view_dancer'),
    path('dancers/<int:dancer_pk>/<int:couple_pk>/', views.view_dancer, name='view_dancer'),    
    path('dancers/edit/<int:dancer_pk>', views.edit_dancer, name='edit_dancer'),
    path('dancers/create/', views.create_dancer, name='create_dancer'),
    path('dancers/create/<str:name_str>/<int:comp_pk>', views.create_dancer, name='create_dancer'),
    path('couples/', views.all_couples, name="all_couples"),
    path('couples/<int:couple_pk>', views.view_couple, name='view_couple'),
    path('couples/<int:couple_pk>/combine/<int:couple2_pk>', views.combine_couples, name='combine_couples'),
    path('couples/flip/<int:couple_pk>', views.flip_couple, name='flip_couple'),
    path('couples/delete/<int:couple_pk>', views.delete_couple, name='delete_couple'),
    path('couples/edit/<int:couple_pk>', views.edit_couple, name='edit_couple'),
    path('couples/change_type/<int:couple_pk>', views.change_couple_type, name='change_couple_type'),
    path('couples/create/', views.create_couple, name='create_couple'),
    path('couples/create/<str:couple_type>/<int:dancer_pk>/<int:dancer_position>/', views.create_couple, name='create_couple'),
    path('couples/create/<str:couple_type>/<int:dancer_pk>/<int:dancer_position>/<int:partner_pk>', views.create_couple, name='create_couple'),
    path('comps/', include('comps.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comps/models/comp.py
from datetime import datetime, timezone
from django.db import models
from cloudinary_storage.storage import RawMediaCloudinaryStorage
from cloudinary.models import CloudinaryField

def comp_logo_path(instance, filename):
    return "comps/{0}/{1}".format(instance.title, filename)

class Comp(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()

    logo = CloudinaryField('logo', blank=True)

    # the different file formats pointed to by the URLs
    COMP_MNGR = 'CM'
    COMP_ORG = 'CO'
    DANCE_COMP = 'DC'
    NDCA_FEED = 'NF'
    O2CM = "O2"
    DATA_FORMAT_CHOICES = [
        (COMP_MNGR, 'Comp Manager'),
        (COMP_ORG, 'Comp Organizer'),
        (DANCE_COMP, 'DanceComp'),
        (NDCA_FEED , 'NDCA Premier'),
        (O2CM, 'O2cm.com')
    ]
    url_data_format = models.CharField(
        max_length=2,
        choices=DATA_FORMAT_CHOICES,
        default=COMP_MNGR,
        )

    # URLs are optional, blank=True allows that, use heatlist_file if URL not available
    heatsheet_url = models.URLField(blank=True)
    heatsheet_file = models.FileField(upload_to=comp_logo_path, blank=True, storage=RawMediaCloudinaryStorage())

    # this field indicates when the heatsheet was loaded
    default_time = datetime(1970,1,1,tzinfo=timezone.utc)
    heatsheet_load_time = models.DateTimeField(null=True, default=default_time)

    scoresheet_url = models.URLField(blank=True)
    scoresheet_file = models.FileField(upload_to=comp_logo_path, blank=True, storage=RawMediaCloudinaryStorage())

    # the different states of processing a competition
    INITIAL = "IN"
    DANCERS_LOADED = "DL"
    DANCER_NAMES_FORMATTED = "DNF"
    HEATS_LOADED = "HL"
    HEAT_STYLES_DEFINED = "HSD"
    HEAT_LEVELS_DEFINED = "HLD"
    HEAT_ENTRIES_MATCHED = "CEM"
    SCORESHEETS_LOADED = "SSL"
    RESULTS_RESOLVED = "RR"
    ELO_RATINGS_UPDATED = "ELO"
    COMPLETE = "FIN"
    PROCESS_STATE_CHOICES = [
        (INITIAL, 'Comp Initialized'),
        (DANCERS_LOADED, 'Dancers Loaded'),
        (DANCER_NAMES_FORMATTED, 'Dancer Names Formatted'),
        (HEATS_LOADED, 'Heats Loaded'),
        (HEAT_STYLES_DEFINED, 'Heat Styles Defined'),
        (HEAT_LEVELS_DEFINED, 'Heat Levels Defined'),
        (HEAT_ENTRIES_MATCHED, 'Heat Entries Matched'),
        (SCORESHEETS_LOADED, 'Scoresheets Loaded'),
        (RESULTS_RESOLVED, 'Results Resolved '),
        (ELO_RATINGS_UPDATED, 'Elo Ratings Updated '),
        (COMPLETE, 'Processing Complete')
    ]

    process_state = models.CharField(
        max_length = 3,
        choices=PROCESS_STATE_CHOICES,
        default=INITIAL,
        )

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['title']

comps/models/heatlist_error.py
from django.db import models
from comps.models.comp import Comp
from comps.models.heat import Heat
from comps.models.heatlist_dancer import Heatlist_Dancer

class Heatlist_Error(models.Model):
    '''Define info about an anomaly found when processing a heatlist.'''

    # the comp where this error was encountered
    comp = models.ForeignKey("comps.Comp", on_delete=models.CASCADE)

    # the heat where this error was encountered
    heat = models.ForeignKey("comps.Heat", on_delete=models.CASCADE, null=True)

    # the dancer's name whose heats were being processed when the error was encountered
    dancer = models.CharField(max_length=100, blank=True)

    # the different errors that may be encountered
    NO_ERROR = "NO_ERR"
    UNKNOWN_LEVEL = "UNK_LEV"
    UNKNOWN_STYLE = "UNK_STYL"
    NO_HEAT_COUNT = "NO_COUNT"
    NO_CODE_FOUND = "NO_CODE"
    NO_PARTNER_FOUND = "NO_PRTNR"
    PARSING_ERROR = "PARS_ERR"
    HEAT_TIME_INVALID = "BAD_TIME"
    ERROR_CHOICES = [
        (NO_ERROR , 'No Error'),
        (UNKNOWN_LEVEL, 'Unknown Event Level'),
        (UNKNOWN_STYLE, 'Unknown Event Style'),
        (NO_HEAT_COUNT, 'Heat Count Not Found'),
        (NO_HEAT_COUNT, 'Scoresheet Code Not Found'),
        (NO_PARTNER_FOUND, 'Partner Not Found'),
        (PARSING_ERROR, 'Unable to Parse Heat'),
        (HEAT_TIME_INVALID, 'Invalid Heat Time')
    ]

    error = models.CharField(
        max_length = 8,
        choices=ERROR_CHOICES,
        default="NO_ERR",
        )

comps/views/all_comps.py
from django.core.paginator import Paginator
from django.shortcuts import render
from comps.models.comp import Comp
from comps.filters import CompFilter

def all_comps(request):
    # only show add button and process state for valid users
    superuser_access = request.user.is_superuser

    # get the list of comps, potentially filtered
    f = CompFilter(request.GET, queryset=Comp.objects.all().order_by('-start_date', 'title'))
    
    paginator = Paginator(f.qs, 16)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "comps/all_comps.html", {'page_obj': page_obj, 'superuser_access': superuser_access, 'filter': f})

comps/views/clear_comp.py
from django.core import serializers
from django.shortcuts import render
from comps.models.comp import Comp
from comps.models.heat import Heat
from comps.models.heatlist_error import Heatlist_Error
from comps.tasks import clear_comp_task

def clear_comp(request, comp_id):
    if not request.user.is_superuser:
        return render(request, 'rankings/permission_denied.html')
    comp_objects = Comp.objects.filter(pk=comp_id)
    if len(comp_objects) == 1:
        comp=comp_objects[0]

    # delete any heatlist errors associated with this comp
    Heatlist_Error.objects.filter(comp=comp).delete()

    # find all the heats in this comp
    heats = Heat.objects.filter(comp=comp)

    comp_data = serializers.serialize("json", comp_objects)
    heat_data = serializers.serialize("json", heats)

    result = clear_comp_task.delay(comp_data, heat_data)

    return render(request, 'comps/process_clear_comp.html', context={'task_id': result.task_id, 'comp': comp})

comps/views/combine_heats.py
from django.shortcuts import render, redirect, get_object_or_404
from comps.models.comp import Comp
from comps.models.heat import Heat
from comps.models.heat_entry import Heat_Entry
from comps.forms import CompForm, HeatForm
from rankings.models.couple import Couple


def combine_heats(request, comp_id):
    if not request.user.is_superuser:
        return render(request, 'rankings/permission_denied.html')

    comp = get_object_or_404(Comp, pk=comp_id)
    heats_in_comp = Heat.objects.filter(comp=comp).order_by('heat_number')
    current_heat_number = 0
    for heat in heats_in_comp:
        if heat.info_prefix() != heat.info:
            if heat.heat_number != current_heat_number:
                current_heat_number = heat.heat_number
                print("Processing Heat "+ current_heat_number)
                possible_matches = list()
            for match in possible_matches:
                if heat.info_prefix() == match.info_prefix():
                    if request.method == "GET":
                        print("Found " + heat.category + " " + str(heat.heat_number) + " " + heat.info)
                        print("Match! " + match.category + " " + str(match.heat_number) + " " + match.info)
                        return render(request, 'comps/combine_heats.html', {'heats': (heat, match)})
                    else:  # POST
                        submit = request.POST.get("submit")
                        if submit == "Skip":
                            return redirect ('comps:heat', heat.id)
                        elif submit == "Submit":
                            heat.remove_info_prefix()
                            print("Combine " + heat.category + " " + heat.heat_number + " " + heat.info)
                            heat.save()
                            matching_entries = Heat_Entry.objects.filter(heat=match).order_by('shirt_number')
                            for e in matching_entries:
                                print(e.couple + " " + e.code + " " + e.shirt_number)
                                e.heat = heat
                                print(e.heat.info)
                                e.save()
                            match.delete()
                            return redirect ('comps:heat', heat.id)
            else:
                possible_matches.append(heat)

    return redirect ('comps:comp_heats', comp_id)

comps/views/comp_detail.py
from django.shortcuts import render, get_object_or_404
from comps.models.comp import Comp

def comp_detail(request, comp_id):
    # only show load dancer, load heat buttons for valid users
    show_load_buttons = request.user.is_superuser
    show_load_time = False

    comp = get_object_or_404(Comp, pk=comp_id)
    
    if comp.heatsheet_load_time is not None:
        if comp.heatsheet_load_time > Comp.default_time:
            show_load_time = True

    return render(request, "comps/comp_detail.html", {'comp':comp, 'show_load_buttons': show_load_buttons, 'show_load_time': show_load_time})

comps/views/comp_heats.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from comps.models.comp import Comp
from comps.models.heat import Heat
from comps.filters import HeatFilter


def comp_heats(request, comp_id):
    comp = get_object_or_404(Comp, pk=comp_id)
    
    # only show elo column for valid users
    show_elo = request.user.is_superuser
    
    f = HeatFilter(request.GET, queryset=Heat.objects.filter(comp=comp).order_by('time', 'heat_number', 'info'))
    paginator = Paginator(f.qs, 16)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "comps/comp_heats.html", {'comp': comp, 'page_obj': page_obj, 'show_elo': show_elo, 'filter': f})

comps/views/couple_heats.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from comps.models.comp import Comp
from comps.models.heat import Heat
from comps.models.heat_entry import Heat_Entry
from rankings.models.couple import Couple
from comps.filters import HeatFilter


def couple_heats(request, comp_id, couple_id):
    # only show add button for valid users
    show_add_button = request.user.is_superuser

    comp = get_object_or_404(Comp, pk=comp_id)
    couple = get_object_or_404(Couple, pk=couple_id)
    
    results_available = comp.process_state in [Comp.RESULTS_RESOLVED, Comp.ELO_RATINGS_UPDATED, Comp.COMPLETE]

    heat_entries = Heat_Entry.objects.filter(heat__comp=comp, couple=couple).order_by('heat__time')
    paginator = Paginator(heat_entries, 16)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "comps/couple_heats.html", {'comp': comp, 'page_obj': page_obj, 'couple': couple, 
                                                       'show_add_button': show_add_button, 
                                                       'results_available': results_available})

comps/templates/comps/comp_detail.html
{% extends "rankings/base.html" %}
{% load static %}
{% load cloudinary %}
{% block content %}
<div class="row">

  {% if comp.logo != "" %}
    <div class="d-none d-md-block col-12 p-0 text-center">
      {% cloudinary comp.logo.public_id  height=324 width=576 crop="fit" %}
    </div>
    <div class="d-block d-md-none col-12 p-0 text-center">
      {% cloudinary comp.logo.public_id  height=180 width=320 crop="fit" %}
    </div>
  {% endif %}
</div>

<div class="row">
  <div class="col-12">
    <h2 class="text-center">{{ comp.title }}</h2>
    <h3 class="text-center">{{ comp.location }}</h3>
    {% if comp.start_date == comp.end_date %}
      <h4 class="text-center">{{ comp.start_date }}</h4>
    {% else %}
      <h4 class="text-center">{{ comp.start_date }} to {{ comp.end_date }}</h4>
    {% endif %}
    {% if show_load_time %}
      <h4 class="text-center">Heats Loaded at {{ comp.heatsheet_load_time }}</h4>
    {% endif %}
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-6 col-sm-3 text-center">
    <h4><a href={{comp.heatsheet_url}} target="_blank">Heat Lists</a></h4>
  </div>
  <div class="col-6 col-sm-3 text-center">
    <h4><a href={{comp.scoresheet_url}} target="_blank">Scoresheets</a></h4>
  </div>
</div>


<div class="row">
  <div class="col-12 text-center my-3">
    {% if show_load_buttons %}
      <span class="dropdown">
        <button class="btn btn-warning dropdown-toggle" type="button" id="editDropdownActionButton" data-toggle="dropdown">Edit</button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'comps:create_heat' comp.id %}">Add Heat</a>
          <a class="dropdown-item" href="{% url 'comps:edit_comp' comp.id %}">Comp Info</a>
          <a class="dropdown-item" onclick="return confirm('Are you sure?')" href="{% url 'comps:clear_comp' comp.id %}">Clear All Data</a>
          <a class="dropdown-item" href="{% url 'comps:this_year_comp' comp.id %}">Create for This Year</a>        
        </div>
      </span>

      {% if comp.heatsheet_url or comp.heatsheet_file %}
        <span class="dropdown">
          <button class="btn btn-info dropdown-toggle" type="button" id="loadDropdownActionButton" data-toggle="dropdown">Load</button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'comps:load_dancers' comp.id %}">Dancers</a>
            <a class="dropdown-item" href="{% url 'comps:load_heats' comp.id %}">Heats</a>
            {% if comp.scoresheet_url or comp.scoresheet_file %}
              <a class="dropdown-item" href="{% url 'comps:load_scoresheets' comp.id %}">Scoresheets</a>
            {% endif %}
          </div>
        </span>
      {% endif %}
      
      {% if comp.heatsheet_url %}
        <span class="dropdown">
          <button class="btn btn-info dropdown-toggle" type="button" id="loadDropdownActionButton" data-toggle="dropdown">Save</button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'comps:save_heatlists' comp.id %}">Heatlists</a>
            {% if comp.scoresheet_url %}
              <a class="dropdown-item" href="{% url 'comps:save_scoresheets' comp.id %}">Scoresheets</a>
            {% endif %}
          </div>
        </span>
      {% endif %}

      <span class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" id="resolveDropdownActionButton" data-toggle="dropdown">Resolve</button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'alias_dancers' 2 %}">Dancer Alias Names</a>
          <a class="dropdown-item" href="{% url 'comps:fix_dup_entries' comp.id %}">Duplicate Entries</a>
          <a class="dropdown-item" href="{% url 'comps:show_heatlist_errors' comp.id %}">Heatlist Errors</a>
          <a class="dropdown-item" href="{% url 'comps:resolve_mismatches' comp.id %}">Mismatched Entries</a>
          <a class="dropdown-item" href="{% url 'comps:show_scoresheet_errors' comp.id %}">Scoresheet Errors</a>
          {% if comp.process_state == comp.RESULTS_RESOLVED %}
            <a class="dropdown-item" href="{% url 'comps:update_elo_ratings' comp.id %}">Update Elo Ratings</a>
          {% endif %}
        </div>
      </span>
      <span class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" id="viewDropdownActionButton" data-toggle="dropdown">View</button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'comps:dancers' comp.id %}">Dancers</a>
          <a class="dropdown-item" href="{% url 'comps:couples' comp.id %}">Couples</a>
          {% if comp.process_state == comp.RESULTS_RESOLVED or comp.process_state == comp.ELO_RATINGS_UPDATED %}
            <a class="dropdown-item" href="{% url 'comps:comp_heats' comp.id %}">Results</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'comps:comp_heats' comp.id %}">Program</a>
          {% endif %}
        </div>
      </span>
    {% else %}
      <div class="row">
        <div class="col-12 text-center">
          <a class="btn btn-info" href="{% url 'comps:dancers' comp.id %}">Dancers</a>
          <a class="btn btn-info" href="{% url 'comps:couples' comp.id %}">Couples</a>
          {% if comp.process_state == comp.RESULTS_RESOLVED or comp.process_state == comp.ELO_RATINGS_UPDATED %}
            <a class="btn btn-info" href="{% url 'comps:comp_heats' comp.id %}">Results</a>
          {% else %}
            <a class="btn btn-info" href="{% url 'comps:comp_heats' comp.id %}">Program</a>
          {% endif %}
        </div>
      </div>
    {% endif %}
  </div>
</div>



{% endblock %}

{% block extra_js %}
<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
<script>
  console.log("Running JS")
  var process_state = '{{ comp.process_state }}';
  if (process_state === '{{ comp.INITIAL }}') {
    $( '#loadDropdownActionButton' ).removeClass( "btn-info" );
    $( '#loadDropdownActionButton' ).addClass( "btn-primary" );
  } else if (process_state === '{{ comp.DANCERS_LOADED }}' || process_state === '{{ comp.DANCER_NAMES_FORMATTED }}') {
    $( '#loadDropdownActionButton' ).removeClass( "btn-info" );
    $( '#loadDropdownActionButton' ).addClass( "btn-primary" );
  } else if (process_state === '{{ comp.HEATS_LOADED}}') {
    $( '#resolveDropdownActionButton' ).removeClass( "btn-info" );
    $( '#resolveDropdownActionButton' ).addClass( "btn-primary" );
  } else if (process_state === '{{ comp.HEAT_ENTRIES_MATCHED}}' || process_state === '{{ comp.HEAT_STYLES_DEFINED }}' || process_state === '{{ comp.HEAT_LEVELS_DEFINED }}') {
    $( '#viewDropdownActionButton' ).removeClass( "btn-info" );
    $( '#viewDropdownActionButton' ).addClass( "btn-primary" );
    $( '#loadDropdownActionButton' ).removeClass( "btn-info" );
    $( '#loadDropdownActionButton' ).addClass( "btn-primary" );
  } else if (process_state === '{{ comp.SCORESHEETS_LOADED}}') {
    $( '#resolveDropdownActionButton' ).removeClass( "btn-info" );
    $( '#resolveDropdownActionButton' ).addClass( "btn-primary" );
    $( '#viewDropdownActionButton' ).removeClass( "btn-info" );
    $( '#viewDropdownActionButton' ).addClass( "btn-primary" );
  } else if (process_state === '{{ comp.RESULTS_RESOLVED}}') {
    $( '#viewDropdownActionButton' ).removeClass( "btn-info" );
    $( '#viewDropdownActionButton' ).addClass( "btn-primary" );
  }
</script>


{% endblock %}

comps/templates/comps/create_heat.html
{% extends "rankings/base.html" %}

{% block content %}

<div class="row">
  <div class="col">
    <h2 class="text-center"><a class=text-dark href="{% url 'comps:comp_detail' comp.id %}">{{ comp.title }}</a></h2>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 offset-3 border border-dark">
    <h3 class="text-center">Create Heat Data</h3>
    <p>{{ error }}</p>

    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" name="submit" value = "Save"/>
    </form>
  </div>
</div>

{% endblock %}

comps/templates/comps/edit_heat.html
{% extends "rankings/base.html" %}

{% block content %}

<div class="row">
  <div class="col">
    <h2 class="text-center"><a class=text-dark href="{% url 'comps:comp_detail' heat.comp.id %}">{{ heat.comp.title }}</a></h2>
    <h3 class="text-center">{{ heat.get_category_display }} {{ heat.heat_number}} {{ heat.info }}</h3>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 offset-3 py-2 border border-dark">
    {% if error %}
      <p class="text-center bg-warning">{{ error.get_error_display }}</p>
    {% endif %}
    <h3 class="text-center">Edit Heat Data</h3>
    
    <p>{{ form_error }}</p>
    <form class="text-center" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" name="submit" value = "Save"/>
      <input class="btn btn-warning" type="submit" name="submit" value = "Add Couple"/>
      <input class="btn btn-danger" type="submit" name="submit" value="Delete Heat" onclick="return confirm('Are you sure?')" />
    </form>
  </div>
</div>

{% endblock %}